### ISSUE TITLE
Help with integrating 

### ISSUE THREAD

**Issue by StargateMC** [LordFokas/StargateTech2#117]
Hi Man

What methods do I need to call to target and active rings ?

I'm trying to set up NPC Ai to use stargates and rings, stargates work but rings I'm having trouble.

Any assistance will be appreciated

**Comment by LordFokas** [comment]
Well, damn. That's complicated.

Rings don't currently have a public API because they're triggered by a key press on the client.

However, rings respond to abstract bus messages, if you're going to do it with the current code, that's your entry point.

**Comment by StargateMC** [comment]
So.... your telling me I cannot call something like teleport() while I grab the Ring tile entity to trigger them? :(

**Comment by LordFokas** [comment]
Here... https://github.com/LordFokas/StargateTech2/blob/master/src/main/java/lordfokas/stargatetech2/transport/TileTransportRing.java#L134

You can only call this on the server. But you need to explicitely build against the mod code or use reflection to invoke the method... neither option really good :/

I promise to get a better public API going as soon as I pick the mod back up and finish v0.8.0
