### ISSUE TITLE
Opencomputers

### ISSUE THREAD

**Issue by Cronosus** [LordFokas/StargateTech2#120]
Please, make it work with OC.
I think, OC is better mod than CC.
thanks

**Comment by SuPeRMiNoR2** [comment]
That should not take long, since it already does.

**Comment by LizzyTrickster** [comment]
What @SuPeRMiNoR2 said. it's not working give version numbers of Oc, stargate tech and mc

Edit: Fuck you phone

**Comment by Cronosus** [comment]
MC 1.7.10
stargatetech2 0.7.8 
OpenComputers 1.6.0.6-beta.4-universal

**Comment by SuPeRMiNoR2** [comment]
I just tested it with those mod versions and it worked for me. Are you aware you need an abstract bus card in your computer, then wire the computer to the gate with abstract bus cable.

**Comment by Cronosus** [comment]
but i want to control shields, not gate
anyway, abstract bus cable not connect to computer

**Comment by SuPeRMiNoR2** [comment]
They can be controlled via abstract bus as well.

Edit: you just have to send them "enable" or "disable" on the bus.
![Like This](https://cloud.githubusercontent.com/assets/3661948/17080536/7222607e-50f9-11e6-8d42-188ad4c165ce.PNG)

**Comment by Cronosus** [comment]
ok, i tried tht again, and cable coonect, but still not working, maybe i do something wrong:
component.abstract_bus.sendPacket("FFFF" , "action: start")

edit: thanks, finally working. :)

**Comment by SuPeRMiNoR2** [comment]
No problem. By the way, if you don't have a problem any more, you might want to close the issue.

**Comment by Cronosus** [comment]
yes, sorry and thanks
