### ISSUE TITLE
Abstract Bus Adapter disappearing when wrapped on a side

### ISSUE THREAD

**Issue by downslope7** [LordFokas/StargateTech2#99]
It looks like the Abstract Bus Adapter disappears from ComputerCraft in certain cases when you wrap it directly on the side of a computer and then do a block update to a block adjacent to the computer.

Steps to reproduce:

1. Place an Abstract Bus Adapter on the left of an Advanced Computer. Open the lua REPL and wrap it. It should show up with no problem.
2. Put a block in front of the Advanced Computer's screen then re-open the computer's GUI.
3. Attempt to wrap the Bus Adapter again. `peripheral.wrap` returns null.

This can be seen (although in this case I removed the block in front of the computer after the first wrap) here: ![so delicious](https://i.imgur.com/gLffZ2i.png)

**Comment by LordFokas** [comment]
This has to be CC's fault, as I don't even mess with peripheral logic.
I just implement an interface that basically tells the computer "hey, here's what I can do".

**Comment by fnuecke** [comment]
I do have a suspicion: maybe CC tries to refresh its adjacent peripherals before detaching from the old ones. In which case [this](http://git.io/FlKC) will cause it to think the peripheral is gone, consequently killing off the old one, and seeing no bus adapters at all anymore.

**Comment by LordFokas** [comment]
Well it's still CC being retarded.
